### PR TITLE
Disable readme build for ghcjs

### PR DESCRIPTION
**Pull request by luigy**

### CODE REVIEW

**Comment by luigy** [comment]
This is not required anymore after https://github.com/obsidiansystems/rhyolite/blob/e9f74763c18f0f8d0d396dd5c9c2db720bccecbf/default.nix#L101-L104

**Comment by ryantrinkle** [comment]
What's wrong with building it for GHCJS?

**Comment by luigy** [comment]
Hmm builds fine in ghcjs with some overrides after cabal2nix that's why I'm closing this

**Comment by ryantrinkle** [comment]
Oh, I didn't read the code, just the title of the PR.  Doesn't this change *enable* building the readme?

**Pull request closed without merging**
